TRservicios/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("servicios.urls")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

servicios/urls.py
from django.urls import path


from . import views

app_name = "sev"
urlpatterns = [
    path("", views.index, name="index"),
    path("servicio/<str:servicio>", views.servicio, name="servicio"),
]

servicios/models.py
from django.db import models

# Create your models here.
class Servicios(models.Model):
	servicio = models.CharField(max_length=64)
	descripcion = models.TextField()
	imgprincipal = models.ImageField(upload_to='galeria', verbose_name='Principal', default='gallery/static/images/no-img.jpg')

	def __str__(self):
		return f"{self.id}:{self.servicio}"

class ImagenesPrincipales(models.Model):
	principal = models.ImageField(upload_to='inicio', verbose_name='Principal', default='gallery/static/images/no-img.jpg')
	descripcion = models.TextField()
	referencia = models.ForeignKey(Servicios, on_delete=models.CASCADE, related_name="inicioServicio")

	def __str__(self):
		return f"{self.principal} hace referencia a {self.referencia}"

class Imagenes(models.Model):	
	imagen = models.ImageField(upload_to='images', verbose_name='Imagenes')
	servicio = models.ForeignKey(Servicios, on_delete=models.CASCADE, related_name="imgServicio")
	descripcion = models.TextField(blank = True, null=True)

	def __str__(self):
		return f"Imagenes de este servicio= {self.servicio}"
		

servicios/forms.py
from django import forms

class Consulta(forms.Form):
    nombre = forms.CharField(max_length=64,  required=True, label=False) 
    email = forms.EmailField(max_length=80,  required=True, label=False)
    msg = forms.CharField(widget=forms.Textarea(attrs={"rows":5, "cols":20}), required=True, label=False)

    def __init__(self, *args, **kwargs):
        super(Consulta, self).__init__(*args, **kwargs)
        self.fields['marca'].widget.attrs = {
            'class': 'form-control',
            'placeholder': 'Nombre'
        }
        self.fields['email'].widget.attrs = {
            'class': 'form-control',
            'type': 'email',
            'placeholder': 'E-mail',
            'id' : 'exampleFormControlInput1'
        }
        self.fields['msg'].widget.attrs = {
            'class': 'form-control',
            'placeholder': 'Escriba su consulta',
            'id' : 'exampleFormControlTextarea1'
        }
    

servicios/views.py
from django.shortcuts import render

from .models import Servicios, Imagenes, ImagenesPrincipales

from .forms import Consulta

# Create your views here.
def index(request):
	return render(request, "servicios/index.html",{
		"servicio": Servicios.objects.all(),
		"banner": ImagenesPrincipales.objects.all(),
		})

def servicio(request, servicio):
	form = Consulta()
	servicioSeleccionado = Servicios.objects.filter(servicio=servicio)
	lisImagenes = Imagenes.objects.filter(servicio__in=servicioSeleccionado).all()
	return render(request, "servicios/servicio.html",{
		"servicio": servicioSeleccionado,
		"img": lisImagenes,
		"form": form
		})

servicios/templates/servicios/index.html
{% extends "servicios/layout.html" %}

{% block body %}
{% load static %}

<div class="slides">
	<!-- Slide pages -->
<div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner">
    	{% for ban in banner %}
        <div class="carousel-item {% if forloop.first %}
      								active
    							  {% endif %}">
            <img class="d-block w-100" src="{{ban.principal.url}}" alt="Impermeabilización de edificios">
            <div class="carousel-caption d-md-block">
                <h5>{{ ban.referencia.servicio }}</h5>
                <p>{{ ban.descripcion }}</p>
            </div>
        </div>
        {% endfor %}

        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        	<span class="carousel-control-prev-icon" aria-hidden="true"></span>
        	<span class="sr-only">Siguiente</span>
    	</a>
    	<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        	<span class="carousel-control-next-icon" aria-hidden="true"></span>
        	<span class="sr-only">Anterior</span>
   		</a>
    </div>
</div>
</div>


 <div class="container marketing">
 	<div class="titleContainer">
 		<h3 class="ourJobs">Nuestros servicios.</h3>
 	</div>
        <!-- Three columns of text below the carousel -->
        <div class="row">
        {% for servi in servicio %}
          <div class="col-lg-4">
            <a href="{% url 'sev:servicio' servi.servicio %}"><img class="rounded-circle" src="{{servi.imgprincipal.url}}" alt="Generic placeholder image" width="140" height="140"></a>
            <div class="text">
            <h3>{{ servi.servicio }}</h3>
            <p>{{ servi.descripcion }}</p>
            <p><a class="btn btn-secondary" href="{% url 'sev:servicio' servi.servicio %}" role="button">Ver detalles &raquo;</a></p>
            </div>
          </div><!-- /.col-lg-4 -->
          {% endfor %}
          
          </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->


        <!-- START THE FEATURETTES -->

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">Recursos humanos de la empresa.</h2>
            <p class="lead">Tenemos al servicio gente de primera calidad en todos los sectores. Contamos con ingenieros electronicos, civiles, licenciados en seguridad e higiene y muchos mas.</p>
            <p><a class="btn btn-secondary" href="#" role="button">Ver lista completa &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <img class="featurette-image img-fluid mx-auto" src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTCRxPbYQqh1mv4HxbqSjPy_ZYVp8ouIk61dw&usqp=CAU" alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">

       <!-- START THE FEATURETTES -->

        <hr class="featurette-divider">

        <div class="row featurette">
        	<div class="col-md-4">
            <img class="featurette-image img-fluid mx-auto" src="https://i2.wp.com/bdmingenieria.com/wp-content/uploads/2020/02/instalaciones-9.jpg?fit=1920%2C1080&ssl=1" alt="Generic placeholder image">
          </div>
          <div class="col-md-7">
            <h2 class="featurette-heading">Generamos confianza</h2>
            <p class="lead">Contamos con la plena confianza de varios empresas que trabajaron y trabajan con nosotros como YPF, (otro) y (otro).</p>
            <p><a class="btn btn-secondary" href="#" role="button">Ver lista completa &raquo;</a></p>
          </div>
          
        </div>

        <hr class="featurette-divider">
       </div>
   </div>


{% endblock %}

servicios/templates/servicios/layout.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
  <head>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'servicios/styles.css' %}" rel="stylesheet">

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<title>Tecnica R. Soluciones</title>
  <meta name="description=" content="Tecnica R. Soluciones te brinda todo tipo de soluciones, teniendo servicios en varios sectores y contando con un gran grupo de trabajo dispuesto a ayudar en lo que sea que el cliente necesite.">

</head>
<body>
	
	<!-- Navbar -->
	<nav class="navbar navbar-expand-md sticky-top navbar-dark bg-dark ">
  		<a id="nombrePage" class="navbar-brand" href="{% url 'sev:index' %}">Tecnica R. Soluciona</a>
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    	<span class="navbar-toggler-icon"></span>
  		</button>
  		<div class="collapse navbar-collapse" id="navbarNav">
    		<ul class="navbar-nav mr-auto">
      			<li class="nav-item active">
        			<a class="nav-link" href="{% url 'sev:index' %}">Inicio<span class="sr-only">(current)</span></a>
      			</li>
      			<li class="nav-item">
        			<a class="nav-link" href="#">Recursos humanos</a>
      			</li>
      			<li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Servicios
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% for servicio in servi %}
                <a class="dropdown-item" href="{% url 'sev:servicio' servicio.servicio %}">{{ servicio.servicio }}</a>
                {% endfor %}
              </div>
            </li>
    		</ul>
    	</div>
    	<form class="form-inline my-2 my-md-0">
      		<input class="form-control mr-sm-2" type="search" placeholder="Buscar..." aria-label="Search">
      		<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
    	</form>   		
	</nav>
<div id="circles">
	{% block body %}
  {% endblock %}
</div>

<footer class="footer mt-auto py-3">
      <div class="container">
        <span class="text-dark">Place sticky footer content here.</span>
      </div>
</footer>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

servicios/templates/servicios/servicio.html
{% extends "servicios/layout.html" %}

{% block body %}
{% load static %}
<div class="slides">
	<!-- Slide pages -->
<div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner">
    	{% for serv in servicio %}
    	{% for image in img %}
        <div class="carousel-item {% if forloop.first %}
      								active
    							  {% endif %}">
            <img class="d-block w-100" src="{{image.imagen.url}}" alt="{{serv.servicio}}">
            <div class="carousel-caption d-md-block">
                <h5>{{ serv.servicio }}</h5>
            </div>
        </div>
        {% endfor %}
     	{% endfor %}

        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        	<span class="carousel-control-prev-icon" aria-hidden="true"></span>
        	<span class="sr-only">Siguiente</span>
    	</a>
    	<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        	<span class="carousel-control-next-icon" aria-hidden="true"></span>
        	<span class="sr-only">Anterior</span>
   		</a>
    </div>
</div>
</div>
{% for serv in servicio %}
<p style="padding: 1.5rem;"> {{ serv.descripcion }}</p>
{% endfor %}
<div class="form">
<form action="" method="post">
	{{ form.non_field_errors }}
	{% csrf_token %}
	{{ form.message.errors }}
  	<div class="col-sm-6">
  		{{ form.nombre }}
  	</div>
  	<div class="col-sm-6">
  		{{ form.email }}
  	</div>
  	<div class="col-sm-6">
  		{{ form.msg }}
  	<button type="submit" class="btn btn-primary mb-2">Enviar</button>
 </form> 
</div>	
{% endblock %}